Repository Kitware/kwiver, pull requests merged in 2018-11, with the labels that each got.

#445 Add kwiver applet runner excutable.
  CMakeLists.txt
  tools/CMakeLists.txt
  tools/applet_context.h
  tools/config_explorer.cxx
  tools/config_explorer.h
  tools/dump_klv-sample.config
  tools/dump_klv.cxx
  tools/dump_klv.h
  tools/kwiver_applet.cxx
  tools/kwiver_applet.h
  tools/kwiver_tool_runner.cxx
  tools/register_tools.cxx
  vital/kwiversys/CommandLineArguments.cxx
  vital/kwiversys/CommandLineArguments.hxx.in
  vital/tools/CMakeLists.txt
Labels: enhancement

#532 Add extra inputs to kwa process, and a few basic vital typedefs
  sprokit/processes/kwiver_type_traits.h
  sprokit/processes/vxl/kw_archive_writer_process.cxx
  sprokit/processes/vxl/kw_archive_writer_process.h
  vital/vital_types.h
Labels: workflow:needs-rework

#652 Convert merge detections process to N way merge.
  sprokit/processes/core/deserializer_process.cxx
  sprokit/processes/core/merge_detection_sets_process.cxx
  sprokit/processes/core/merge_detection_sets_process.h
  sprokit/processes/core/register_processes.cxx
Labels: workflow:in-review

#675 Mesh Triangulation
  arrows/core/CMakeLists.txt
  arrows/core/mesh_operations.cxx
  arrows/core/mesh_operations.h
  arrows/core/tests/CMakeLists.txt
  arrows/core/tests/test_mesh_operations.cxx
  doc/release-notes/master.txt
  vital/types/mesh.cxx
  vital/types/mesh.h
Labels: enhancement

#679 Fix problem with config block merge.
  vital/config/config_block.cxx
  vital/config/tests/test_config_block.cxx
Labels: bug
