Repository Kitware/kwiver, pull requests merged in 2018-02, with the labels that each got.

#467 Change kpf-yaml target include settings
  arrows/kpf/yaml/CMakeLists.txt
Labels: workflow:in-review

#436 Conceptual implementation for track interpolation
  vital/algo/CMakeLists.txt
  vital/algo/interpolate_track.cxx
  vital/algo/interpolate_track.h
Labels: workflow:WIP

#461 Modify embedded pipeline to allow config update before running.
  sprokit/processes/adapters/embedded_pipeline.cxx
  sprokit/processes/adapters/embedded_pipeline.h
  sprokit/processes/adapters/tests/basic_test.cxx
  sprokit/src/sprokit/pipeline/process.h
Labels: enhancement

#488 Add really dumb track interpolator
  arrows/core/CMakeLists.txt
  arrows/core/interpolate_track_spline.cxx
  arrows/core/interpolate_track_spline.h
  arrows/core/register_algorithms.cxx
  arrows/core/tests/CMakeLists.txt
  arrows/core/tests/test_interpolate_track_spline.cxx
  vital/algo/interpolate_track.h
Labels: workflow:in-review

#483 Add timestamp to object tracks
  vital/bindings/c/types/object_track_set.cxx
  vital/bindings/c/types/object_track_set.h
  vital/bindings/python/vital/types/object_track_set.cxx
  vital/types/object_track_set.h
Labels: workflow:in-review
