Repository Kitware/kwiver, pull requests merged in 2019-01, with the labels that each got.

#705 Fix failing process test.
  sprokit/processes/core/merge_images_process.cxx
  sprokit/processes/core/merge_images_process.h
  sprokit/processes/core/register_processes.cxx
Labels: bug, workflow:in-review

#709 Fix include directive bug
  sprokit/src/sprokit/pipeline_util/lex_processor.cxx
  sprokit/src/sprokit/pipeline_util/lex_processor.h
Labels: bug

#715 Dev/port plugins arrows core
  arrows/core/associate_detections_to_tracks_threshold.h
  arrows/core/class_probablity_filter.h
  arrows/core/close_loops_bad_frames_only.h
  arrows/core/close_loops_exhaustive.h
  arrows/core/close_loops_keyframe.h
  arrows/core/close_loops_multi_method.h
  arrows/core/compute_association_matrix_from_features.h
  arrows/core/compute_ref_homography_core.h
  arrows/core/convert_image_bypass.h
  arrows/core/create_detection_grid.h
  arrows/core/detected_object_set_input_csv.h
  arrows/core/detected_object_set_input_kw18.h
  arrows/core/detected_object_set_input_simulator.h
  arrows/core/detected_object_set_output_csv.h
  arrows/core/detected_object_set_output_kw18.h
  arrows/core/dynamic_config_none.h
  arrows/core/estimate_canonical_transform.h
  arrows/core/example_detector.h
  arrows/core/feature_descriptor_io.h
  arrows/core/filter_features_magnitude.h
  arrows/core/filter_features_scale.h
  arrows/core/filter_tracks.h
  arrows/core/handle_descriptor_request_core.h
  arrows/core/hierarchical_bundle_adjust.h
  arrows/core/initialize_cameras_landmarks.h
  arrows/core/initialize_object_tracks_threshold.h
  arrows/core/interpolate_track_spline.h
  arrows/core/keyframe_selector_basic.h
  arrows/core/match_features_fundamental_matrix.h
  arrows/core/match_features_homography.h
  arrows/core/read_object_track_set_kw18.h
  arrows/core/read_track_descriptor_set_csv.h
  arrows/core/register_algorithms.cxx
  arrows/core/track_features_augment_keyframes.h
  arrows/core/track_features_core.h
  arrows/core/triangulate_landmarks.h
  arrows/core/video_input_filter.h
  arrows/core/video_input_image_list.h
  arrows/core/video_input_pos.h
  arrows/core/video_input_split.h
  arrows/core/write_object_track_set_kw18.h
  arrows/core/write_track_descriptor_set_csv.h
  sprokit/processes/flow/collate_process.h
  sprokit/processes/flow/distribute_process.h
  sprokit/processes/flow/pass_process.h
  sprokit/processes/flow/registration.cxx
  sprokit/processes/flow/sink_process.h
Labels: workflow:in-review

#727 Dev/fix image serializer
  arrows/gdal/image_container.cxx
  arrows/serialize/json/load_save.cxx
  arrows/serialize/json/tests/test_serialize.cxx
  arrows/serialize/protobuf/convert_protobuf.cxx
  arrows/serialize/protobuf/tests/test_serialize.cxx
Labels: workflow:in-review

#731 Add check for file open error and other config file issues
  sprokit/processes/adapters/epx_test.cxx
  vital/config/config_block.cxx
  vital/config/config_block.h
  vital/config/config_block_formatter.cxx
  vital/config/config_block_formatter.h
  vital/config/config_block_io.cxx
Labels: bug, workflow:in-review

#730 Fix returned value type for search path.
  vital/config/config_block_io.cxx
Labels: bug

#729 Update the KPF YAML parser to allow embedded YAML in metadata.
  arrows/kpf/yaml/kpf_yaml_parser.cxx
Labels: workflow:in-review
